apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-prod
spec:
  secretName: client-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: clients.api.deltacapita.com
  dnsNames:
  - clients.api.deltacapita.com
